CREATE DATABASE ALMACEN;
CREATE TABLE Marcas(
    MarcaId INTEGER AUTO_INCREMENT PRIMARY KEY,
    NombreMarca TEXT NOT NULL
);
CREATE TABLE Productos(
    Id INTEGER AUTO_INCREMENT PRIMARY KEY,
    Nombre TEXT NOT NULL,
    Especificaciones TEXT,
    MarcaId INTEGER
);
